name: searchflix
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  cached_network_image: ^3.4.1
  provider: ^6.1.5+1
  intl: ^0.20.2
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  google_generative_ai: ^0.4.5
  font_awesome_flutter: ^10.12.0
  go_router: ^12.0.0
  flutter_web_plugins:
    sdk: flutter
  msix: ^3.16.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.4
  flutter_lints: ^5.0.0

msix_config:
  display_name: SearchFlix
  publisher_display_name: SearchFlix
  publisher: CN=SearchFlix
  identity_name: com.searchflix.app
  msix_version: 1.0.0.0
  logo_path: assets/fonts/Vazirmatn-Regular.ttf # Placeholder for icon until we have a real one

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
        - asset: assets/fonts/Vazirmatn-Light.ttf
          weight: 300
        - asset: assets/fonts/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-Thin.ttf
          weight: 100
